Repository bitcoinops/bitcoinops.github.io, pull requests merged in 2019-12, with the labels that each got.

#279 newsletter-70:add Japanese translation
  _posts/ja/newsletters/2019-10-30-newsletter-ja.md
Labels: localization-japanese

#291 Newsletter-73:Translate into Japanese
  _posts/ja/newsletters/2019-11-20-newsletter-ja.md
Labels: localization-japanese

#290 Newsletters: add 76 (2019-12-11)
  _posts/en/newsletters/2019-12-11-newsletter.md
Labels: Newsletters

#293 Newsletter-74:Translate into Japanese
  _posts/ja/newsletters/2019-11-27-newsletter-ja.md
Labels: localization-japanese

#297 Newsletter-75:Translate into Japanese
  _posts/ja/newsletters/2019-12-04-newsletter-ja.md
Labels: localization-japanese

#305 Newsletter 76:Translate into Japanese
  _posts/ja/newsletters/2019-12-11-newsletter-ja.md
Labels: localization-japanese

#282 Add Wasabi RBF notification support
  _data/compatibility/wasabi.yaml
  img/compatibility/wasabi/rbf/notification-incoming-rbf.png
Labels: Compatibility

#303 compat: add Purse.io info
  _data/compatibility/purse.yaml
  en/compatibility/purse.md
  img/compatibility/purse/purse.png
  img/compatibility/purse/rbf/transaction-list.png
  img/compatibility/purse/segwit/receive-screen-nested.png
  img/compatibility/purse/segwit/receive-screen-p2wpkh.png
  img/compatibility/purse/segwit/send-screen.png
  img/compatibility/purse/segwit/send-v1.png
Labels: Compatibility
