Repository bitcoinops/bitcoinops.github.io, pull requests merged in 2020-03, with the labels that each got.

#361 Members: add Fidelity (FCAT)
  _data/sponsors.yml
  img/members/fcat.png
Labels: website

#362 Newsletter-81:Translate into Japanese
  _posts/ja/newsletters/2020-01-22-newsletter-ja.md
Labels: localization-japanese

#363 Newsletter-82:Translate into Japanese
  _posts/ja/newsletters/2020-01-29-newsletter-ja.md
Labels: localization-japanese

#358 Compatibility: add Kraken
  _data/compatibility/kraken.yaml
  en/compatibility/kraken.md
  img/compatibility/kraken/kraken.png
  img/compatibility/kraken/rbf/send-confirm.png
  img/compatibility/kraken/rbf/transaction-list.png
  img/compatibility/kraken/segwit/create-address.png
  img/compatibility/kraken/segwit/receive-screen.png
  img/compatibility/kraken/segwit/send-screen.png
Labels: compatibility

#364 Newsletter-83:Translate into Japanese
  _posts/ja/newsletters/2020-02-05-newsletter-ja.md
Labels: localization-japanese

#367 Newsletter-84:Translate into Japanese
  _posts/ja/newsletters/2020-02-12-newsletter-ja.md
Labels: localization-japanese

#370 Newsletter-85:Translate into Japanese
  _posts/ja/newsletters/2020-02-19-newsletter-ja.md
Labels: localization-japanese, newsletters

#371 Newsletter-86:Translate into Japanese
  _posts/ja/newsletters/2020-02-26-newsletter-ja.md
Labels: localization-japanese, newsletters

#376 Newsletter-87:Translate into Japanese
  _posts/ja/newsletters/2020-03-04-newsletter-ja.md
Labels: localization-japanese

#379 Newsletter-88:Translate into Japanese
  _posts/ja/newsletters/2020-03-11-newsletter-ja.md
Labels: localization-japanese

#380 Newsletter-89:Translate into Japanese
  _posts/ja/newsletters/2020-03-18-newsletter-ja.md
Labels: localization-japanese

#381 Newsletter-90:Translate into Japanese
  _posts/ja/newsletters/2020-03-25-newsletter-ja.md
Labels: localization-japanese
