Repository bitcoinops/bitcoinops.github.io, pull requests merged in 2020-02, with the labels that each got.

#333 Newsletter 79:Translate into Japanese
  _posts/ja/newsletters/2020-01-08-newsletter-ja.md
Labels: localization-japanese

#344 Newsletter-80:Translate into Japanese
  _posts/ja/newsletters/2020-01-15-newsletter-ja.md
Labels: localization-japanese, newsletters

#322 Tools: add crude calculator for transaction size
  en/tools/calc-size.md
Labels: book, website

#352 Config base url change to correct rss feed urls.
  _config.yml
Labels: website

#356 CONTRIBUTING.md : adds detail around internal linking for translations
  CONTRIBUTING.md
Labels: internationalization
